/* ═══════════════════════════════════════════════════════════
   DADOS DO SITE — produtos, cabazes, preços e fotos

   Cada produto tem 4 campos importantes:
     nome  → nome mostrado
     peso  → peso/quantidade (ex: "1 kg", "±500 g", "Caixa 250 g")
     preco → preço para essa quantidade (ex: "1,90 €")
     foto  → chave de FOTOS (a imagem)

   COMO ATUALIZAR UM PREÇO:
     substituir  preco:P  por  preco:"1,90 €"
   `P` é o texto mostrado enquanto o preço não está definido.
   Também pode ajustar `peso` para o peso real de cada produto.
   ═══════════════════════════════════════════════════════════ */
  const P = "A consultar";

  const FOTOS = {
    bananas:      "fotos/foto_8_1.jpeg",
    laranjas:     "fotos/foto_7_1.jpeg",
    morangos:     "fotos/foto_10_1.jpeg",
    melancia:     "fotos/foto_3_1.jpeg",
    ananas:       "fotos/foto_12_1.jpeg",
    pessegos:     "fotos/foto_6_1.jpeg",
    melao_verde:  "fotos/foto_4_1.jpeg",
    melao_branco: "fotos/foto_2_1.jpeg",
    melao_am:     "fotos/foto_5_1.jpeg",
    figos:        "fotos/foto_1_1.jpeg",
    roma:         "fotos/foto_9_1.jpeg",
    tangerina:    "fotos/foto_11_1.jpeg",
    macas:      "fotos/macas.jpeg",
    uvas:       "fotos/uvas.jpeg",
    manga:      "fotos/manga.jpeg",
    peras:      "fotos/peras.jpeg",
    limoes:     "fotos/limoes.jpeg",
    cerejas:    "fotos/cerejas.jpeg",
    kiwi:       "fotos/kiwi.jpeg",
    abacate:    "fotos/abacate.jpeg",
    coco:       "fotos/coco.jpeg",
    ameixa:     "fotos/ameixa.jpeg",
    tomates:    "fotos/tomates.jpeg",
    cenouras:   "fotos/cenouras.jpeg",
    brocoulos:  "fotos/brocolos.jpeg",
    alface:     "fotos/alface.jpeg",
    alface_roxa:"fotos/alface_roxa.jpeg",
    pepino:     "fotos/pepino.jpeg",
    pimentos:   "fotos/pimentos.jpeg",
    cebolas:    "fotos/cebolas.jpeg",
    alho:       "fotos/alho.jpeg",
    batatas:    "fotos/batatas.jpeg",
    milho:      "fotos/milho.jpeg",
    espinafres: "fotos/espinafres.jpeg",
    beringela:  "fotos/beringela.jpeg",
    curgete:    "fotos/curgete.jpeg",
    cogumelos:  "fotos/cogumelos.jpeg",
    couve:      "fotos/couve.jpeg",
    batatadoce: "fotos/batatadoce.jpeg",
    salsa:        "fotos/salsa.jpeg",
    coentros:     "fotos/coentros.jpeg",
    hortela:      "fotos/hortela.jpeg",
    abobora:      "fotos/abobora.jpeg",
    alho_frances: "fotos/alho_frances.jpeg",
    couveflor:    "fotos/couveflor.jpeg",
    feijao_verde: "fotos/feijao_verde.jpeg",
    nabo:         "fotos/nabo.jpeg",
    agriao:       "fotos/agriao.jpeg",
    beterraba:    "fotos/beterraba.jpeg",
    couvecoracao: "fotos/couvecoracao.jpeg",
    couvelombarda:"fotos/couvelombarda.jpeg",
    grelos:       "fotos/grelos.jpeg",
    malagueta:    "fotos/malagueta.jpeg",
    quiabo:       "fotos/quiabo.jpeg",
    rabanete:     "fotos/rabanete.jpeg",
    xuxu:         "fotos/xuxu.jpeg",
    feijao_catarino:"fotos/feijao_catarino.jpeg",
    feijao_dourado: "fotos/feijao_dourado.jpeg",
    feijao_maduro:    "fotos/feijao_maduro.jpeg",
    abobora_cortada:  "fotos/abobora_cortada.jpeg",
    abobora_cabocha:  "fotos/abobora_cabocha.jpeg",
    abobora_butternut:"fotos/abobora_butternut.jpeg",
    cebola_nova:      "fotos/cebola_nova.jpeg",
    gengibre:         "fotos/gengibre.jpeg",
    mandioca:         "fotos/mandioca.jpeg",
    inhame:           "fotos/inhame.jpeg",
    tomate_coracao_boi:"fotos/tomate_coracao_boi.jpeg",
    lima:             "fotos/lima.jpeg",
    tomate_salada:    "fotos/tomate_salada.jpeg",
    tomate_cacho:     "fotos/tomate_cacho.jpeg",
    tomate_chucha:    "fotos/tomate_chucha.jpeg",
    tomate_cereja:    "fotos/tomate_cereja.jpeg",
    pimento_verde:    "fotos/pimento_verde.jpeg",
    pimento_vermelho: "fotos/pimento_vermelho.jpeg",
    batata_agria:     "fotos/batata_agria.jpeg",
    batata_branca:    "fotos/batata_branca.jpeg",
    batata_olho_perdiz:"fotos/batata_olho_perdiz.jpeg",
    batata_vermelha:  "fotos/batata_vermelha.jpeg",
    framboesa:  "fotos/framboesa.jpeg",
    mirtilos:   "fotos/mirtilos.jpeg",
    amoras:     "fotos/amoras.jpeg",
    lichia:     "fotos/lichia.jpeg",
    alperce:    "fotos/alperce.jpeg",
    diospiro:   "fotos/diospiro.jpeg",
    papaia:     "fotos/papaia.jpeg",
    nesperas:   "fotos/nesperas.jpeg",
    maca_verde: "fotos/maca_verde.jpeg",
    pessego_amarelo:  "fotos/pessego_amarelo.jpeg",
    pessego_vermelho: "fotos/pessego_vermelho.jpeg",
    pessego_paraguaio:"fotos/pessego_paraguaio.jpeg",
    nectarina:        "fotos/nectarina.jpeg",
    banana_madeira:   "fotos/banana_madeira.jpeg",
    pera_perola:      "fotos/pera_perola.jpeg",
    ameixa_abrunho:   "fotos/ameixa_abrunho.jpeg",
    mamao:            "fotos/mamao.jpeg",
    maca_pink_lady:   "fotos/maca_pink_lady.jpeg",
    maca_reineta:     "fotos/maca_reineta.jpeg",
    maca_fuji:        "fotos/maca_fuji.jpeg",
    maca_golden:      "fotos/maca_golden.jpeg",
    maca_gala:        "fotos/maca_gala.jpeg",
    cabaz_detox:      "fotos/cabaz_detox.jpeg",
    cabaz_frutas:  "fotos/cabaz_frutas.jpeg",
    cabaz_legumes: "fotos/cabaz_legumes.jpeg",
    cabaz_mix:     "fotos/cabaz_mix.jpeg",
    cabaz_verao:   "fotos/cabaz_verao.jpeg",
  };
  const SFX = "?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop";

  function urlFoto(u) { return u.startsWith('fotos/') ? u : u + SFX; }

  const produtos = {
    // FRUTAS — ordem e preços definidos pelo lojista. Preço por kg (exceto frutos vermelhos, por cuvete).
    // Campo `origem` = país/região de origem (mostrado no cartão).
    frutas: [
      { nome:"Melancia",                emoji:"🍉", peso:"1 kg", preco:"0,99 €", origem:"Marrocos",     foto:FOTOS.melancia,     badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Melancia sem Sementes",   emoji:"🍉", peso:"1 kg", preco:P,                               foto:FOTOS.melancia,     badge:"🌞 Verão",    badgeClass:"" },      { nome:"Melão Branco",            emoji:"🍈", peso:"1 kg", preco:"1,50 €", origem:"Alentejo",     foto:FOTOS.melao_branco, badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Meloa",                   emoji:"🍈", peso:"1 kg", preco:"2,49 €", origem:"Algarve",      foto:FOTOS.melao_am,     badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Morangos",                emoji:"🍓", peso:"1 kg", preco:"4,99 €", origem:"Nacional",     foto:FOTOS.morangos,     badge:"🔥 Popular",  badgeClass:"badge-hot" },
      { nome:"Pêssego Amarelo",         emoji:"🍑", peso:"1 kg", preco:"3,49 €", origem:"Nacional",     foto:FOTOS.pessego_amarelo,  badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Pêssego Vermelho",        emoji:"🍑", peso:"1 kg", preco:"1,99 €", origem:"Nacional",     foto:FOTOS.pessego_vermelho, badge:null },
      { nome:"Pêssego Paraguaio",       emoji:"🍑", peso:"1 kg", preco:"3,49 €", origem:"Nacional",     foto:FOTOS.pessego_paraguaio,badge:null },
      { nome:"Pêssego Rosa",            emoji:"🍑", peso:"1 kg", preco:P,        origem:"Nacional",     foto:FOTOS.pessego_vermelho, badge:null },
      { nome:"Nectarina",               emoji:"🍑", peso:"1 kg", preco:"3,59 €", origem:"Nacional",     foto:FOTOS.nectarina,        badge:null },
      { nome:"Nectarina Premium",       emoji:"🍑", peso:"1 kg", preco:"2,99 €", origem:"Nacional",     foto:FOTOS.nectarina,        badge:"💎 Premium",  badgeClass:"" },
      { nome:"Ameixa Vermelha",         emoji:"🍑", peso:"1 kg", preco:"4,99 €", origem:"Nacional",     foto:FOTOS.ameixa,       badge:null },
      { nome:"Cereja de Fundão",        emoji:"🍒", peso:"1 kg", preco:"6,99 €",                        foto:FOTOS.cerejas,      badge:"💎 Premium",  badgeClass:"badge-hot" },
      { nome:"Cereja Gardunha",         emoji:"🍒", peso:"1 kg", preco:"5,99 €", origem:"Beira",        foto:FOTOS.cerejas,      badge:null },
      { nome:"Uvas sem Grainha",        emoji:"🍇", peso:"1 kg", preco:"5,99 €", origem:"Chile",        foto:FOTOS.uvas,         badge:null },
      { nome:"Figos",                   emoji:"🫐", peso:"1 kg", preco:P,                               foto:FOTOS.figos,        badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Manga Avião",             emoji:"🥭", peso:"1 kg", preco:"5,79 €", origem:"Brasil",       foto:FOTOS.manga,        badge:"🌴 Tropical", badgeClass:"badge-new" },
      { nome:"Abacaxi Maturado",        emoji:"🍍", peso:"1 kg", preco:"2,99 €", origem:"Costa Rica",   foto:FOTOS.ananas,       badge:"💎 Premium",  badgeClass:"" },
      { nome:"Limão",                   emoji:"🍋", peso:"1 kg", preco:"1,59 €", origem:"Nacional",     foto:FOTOS.limoes,       badge:null },
      { nome:"Lima",                    emoji:"🍋", peso:"500 g", preco:"1,99 €",                       foto:FOTOS.lima,         badge:null },
      { nome:"Banana Del Monte",        emoji:"🍌", peso:"1 kg", preco:"1,79 €", origem:"Costa Rica",   foto:FOTOS.bananas,      badge:"💎 Premium",  badgeClass:"" },
      { nome:"Banana Madeira",          emoji:"🍌", peso:"1 kg", preco:"3,59 €",                        foto:FOTOS.banana_madeira, badge:null },
      { nome:"Laranja Algarve",         emoji:"🍊", peso:"1 kg", preco:"1,20 €", origem:"Algarve",      foto:FOTOS.laranjas,     badge:null },
      { nome:"Laranja Algarve Premium", emoji:"🍊", peso:"1 kg", preco:"1,79 €", origem:"Nacional",     foto:FOTOS.laranjas,     badge:"💎 Premium",  badgeClass:"" },
      { nome:"Marcott",                 emoji:"🍊", peso:"1 kg", preco:"2,99 €", origem:"Nacional",     foto:FOTOS.tangerina,    badge:null },
      { nome:"Tangerina",               emoji:"🍊", peso:"1 kg", preco:P,                               foto:FOTOS.tangerina,    badge:null },
      { nome:"Pêra Rocha",              emoji:"🍐", peso:"1 kg", preco:"1,99 €", origem:"Oeste",        foto:FOTOS.peras,        badge:null },
      { nome:"Pêra Premium",            emoji:"🍐", peso:"1 kg", preco:"2,99 €", origem:"Nacional",     foto:FOTOS.peras,        badge:"💎 Premium",  badgeClass:"" },
      { nome:"Pêra Pérola",             emoji:"🍐", peso:"1 kg", preco:"1,69 €", origem:"Espanha",      foto:FOTOS.pera_perola,  badge:"👌 Recomendado", badgeClass:"badge-new" },
      { nome:"Pêra Abate",              emoji:"🍐", peso:"1 kg", preco:"1,99 €",                        foto:FOTOS.peras,        badge:null },
      { nome:"Kiwi Green New Zealand",  emoji:"🥝", peso:"1 kg", preco:"5,99 €", origem:"Nova Zelândia",foto:FOTOS.kiwi,         badge:null },      { nome:"Abacate Hass",            emoji:"🥑", peso:"1 kg", preco:"4,99 €",                        foto:FOTOS.abacate,      badge:"💎 Premium",  badgeClass:"" },
      { nome:"Lichia",                  emoji:"🔴", peso:"1 kg", preco:"5,99 €",                        foto:FOTOS.lichia,       badge:"💎 Premium",  badgeClass:"" },
      { nome:"Ameixa Preta Nacional",   emoji:"🟣", peso:"1 kg", preco:"2,49 €", origem:"Nacional",     foto:FOTOS.ameixa,       badge:null },
      { nome:"Ameixa Branca Nacional",  emoji:"🟡", peso:"1 kg", preco:"1,49 €", origem:"Nacional",     foto:FOTOS.ameixa,       badge:null },
      { nome:"Ameixa Abrunho",          emoji:"🟣", peso:"1 kg", preco:"3,99 €",                        foto:FOTOS.ameixa_abrunho, badge:"👌 Recomendado", badgeClass:"badge-new" },
      { nome:"Alperce Nacional",        emoji:"🍑", peso:"1 kg", preco:"2,99 €", origem:"Nacional",     foto:FOTOS.alperce,      badge:null },
      { nome:"Diospiro Nacional",       emoji:"🟠", peso:"1 kg", preco:"3,99 €", origem:"Nacional",     foto:FOTOS.diospiro,     badge:null },
      { nome:"Mamão",                   emoji:"🥭", peso:"1 kg", preco:"4,79 €",                        foto:FOTOS.mamao,        badge:null },
      { nome:"Papaia",                  emoji:"🥭", peso:"1 kg", preco:"5,49 €",                        foto:FOTOS.papaia,       badge:null },
      { nome:"Romã",                    emoji:"🔴", peso:"1 kg", preco:"4,99 €",                        foto:FOTOS.roma,         badge:null },
      { nome:"Maçã Pink Lady",          emoji:"🍎", peso:"1 kg", preco:"3,99 €",                        foto:FOTOS.maca_pink_lady, badge:null },
      { nome:"Maçã Granny Smith",       emoji:"🍏", peso:"1 kg", preco:"2,99 €",                        foto:FOTOS.maca_verde,   badge:null },
      { nome:"Maçã Golden",             emoji:"🍎", peso:"1 kg", preco:P,                               foto:FOTOS.maca_golden,  badge:null },
      { nome:"Maçã Reineta",            emoji:"🍏", peso:"1 kg", preco:P,                               foto:FOTOS.maca_reineta, badge:null },
      { nome:"Nêsperas Ruchey",         emoji:"🟠", peso:"1 kg", preco:"5,99 €",                        foto:FOTOS.nesperas,     badge:"💎 Premium",  badgeClass:"" },
      { nome:"Maçã Fuji",               emoji:"🍎", peso:"1 kg", preco:"1,89 €",                        foto:FOTOS.maca_fuji,    badge:null },
      { nome:"Maçã Fuji Premium",       emoji:"🍎", peso:"1 kg", preco:"2,99 €",                        foto:FOTOS.maca_fuji,    badge:"💎 Premium",  badgeClass:"" },
      { nome:"Maçã Royal Gala",         emoji:"🍎", peso:"1 kg", preco:"1,69 €",                        foto:FOTOS.maca_gala,    badge:null },
      { nome:"Maçã Golden Rosa Francesa",emoji:"🍎",peso:"1 kg", preco:"4,99 €",                        foto:FOTOS.maca_golden,  badge:"💎 Premium",  badgeClass:"" },
      { nome:"Abacaxi Avião Costa Rica",emoji:"🍍", peso:"1 kg", preco:"6,49 €", origem:"Costa Rica",   foto:FOTOS.ananas,       badge:"💎 Premium",  badgeClass:"" },
      { nome:"Framboesa",               emoji:"🍒", peso:"Cuvete 130 g", preco:"2,29 €",                foto:FOTOS.framboesa,    badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Mirtilos",                emoji:"🫐", peso:"Cuvete 125 g", preco:"2,49 €",                foto:FOTOS.mirtilos,     badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Amoras",                  emoji:"🫐", peso:"Cuvete 150 g", preco:"2,99 €",                foto:FOTOS.amoras,       badge:"🌞 Verão",    badgeClass:"" },
    ],
    // LEGUMES — ordem alfabética. Preço por kg (ervas por molho).
    // LEGUMES — ordem alfabética. Preço por kg; ervas/grelos por molho; couves por unidade.
    legumes: [
      { nome:"Abóbora Butternut",      emoji:"🎃", peso:"1 kg",       preco:"1,49 €", foto:FOTOS.abobora_butternut, badge:null },
      { nome:"Abóbora Cabocha",        emoji:"🎃", peso:"1 kg",       preco:"3,49 €", foto:FOTOS.abobora_cabocha,   badge:null },
      { nome:"Abóbora Fatiada s/ Caroço",emoji:"🎃", peso:"1 kg",     preco:"1,89 €", foto:FOTOS.abobora_cortada,   badge:null },
      { nome:"Abóbora Inteira",        emoji:"🎃", peso:"1 kg",       preco:"1,20 €", foto:FOTOS.abobora,          badge:null },
      { nome:"Agrião",                 emoji:"🌿", peso:"Molho",      preco:"1,50 €", foto:FOTOS.agriao,           badge:null },
      { nome:"Alface",                 emoji:"🥬", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.alface,           badge:null },
      { nome:"Alface Roxa",            emoji:"🥬", peso:"1 un",       preco:"1,60 €", foto:FOTOS.alface_roxa,      badge:null },
      { nome:"Alho Francês",           emoji:"🥬", peso:"500 g",      preco:"1,25 €", foto:FOTOS.alho_frances,     badge:null },
      { nome:"Alho Seco",              emoji:"🧄", peso:"250 g",      preco:"1,65 €", foto:FOTOS.alho,             badge:null },
      { nome:"Batata Agria",           emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_agria,      badge:null },
      { nome:"Batata Branca",          emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_branca,     badge:null },
      { nome:"Batata Doce",            emoji:"🍠", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.batatadoce,       badge:null },
      { nome:"Batata Doce Cor Laranja",emoji:"🍠", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.batatadoce,       badge:null },
      { nome:"Batata Olho de Perdiz",  emoji:"🥔", peso:"1 kg",       preco:"1,79 €", foto:FOTOS.batata_olho_perdiz,badge:null },
      { nome:"Batata Vermelha",        emoji:"🥔", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.batata_vermelha,   badge:null },
      { nome:"Beringela",              emoji:"🍆", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.beringela,        badge:null },
      { nome:"Beterraba",              emoji:"🟣", peso:"1 kg",       preco:"1,69 €", foto:FOTOS.beterraba,        badge:null },
      { nome:"Brócolos sem Folha",     emoji:"🥦", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.brocoulos,        badge:"🌱 Bio",  badgeClass:"badge-bio" },
      { nome:"Cebola Doce",            emoji:"🧅", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.cebolas,          badge:null },
      { nome:"Cebola Nova",            emoji:"🧅", peso:"1 kg",       preco:"1,20 €", foto:FOTOS.cebola_nova,      badge:null },
      { nome:"Cenoura",                emoji:"🥕", peso:"1 kg",       preco:"0,99 €", foto:FOTOS.cenouras,         badge:null },
      { nome:"Chuchu",                 emoji:"🥒", peso:"1 kg",       preco:"3,49 €", foto:FOTOS.xuxu,             badge:null },
      { nome:"Coentros",               emoji:"🌿", peso:"Molho 100g", preco:"1,20 €", foto:FOTOS.coentros,         badge:null },
      { nome:"Cogumelos",              emoji:"🍄", peso:"500 g",      preco:"2,99 €", foto:FOTOS.cogumelos,        badge:null },
      { nome:"Couve Coração",          emoji:"🥬", peso:"1 un",       preco:"1,39 €", foto:FOTOS.couvecoracao,     badge:null },
      { nome:"Couve Lombarda",         emoji:"🥬", peso:"1 un",       preco:"1,39 €", foto:FOTOS.couvelombarda,    badge:null },
      { nome:"Couve Portuguesa",       emoji:"🥬", peso:"1 un",       preco:"1,99 €", foto:FOTOS.couve,            badge:null },
      { nome:"Couve-flor",             emoji:"🥦", peso:"1 un",       preco:"1,99 €", foto:FOTOS.couveflor,        badge:null },
      { nome:"Curgete",                emoji:"🥒", peso:"1 kg",       preco:"1,99 €", foto:FOTOS.curgete,          badge:null },
      { nome:"Espinafres",             emoji:"🥬", peso:"Molho",      preco:"2,49 €", foto:FOTOS.espinafres,       badge:"🌱 Bio",  badgeClass:"badge-bio" },
      { nome:"Feijão Dourado",         emoji:"🫘", peso:"1 kg",       preco:"6,99 €", foto:FOTOS.feijao_dourado,   badge:null },
      { nome:"Feijão Maduro",          emoji:"🫘", peso:"1 kg",       preco:"5,99 €", foto:FOTOS.feijao_maduro,    badge:null },
      { nome:"Feijão Verde",           emoji:"🫛", peso:"1 kg",       preco:"4,99 €", foto:FOTOS.feijao_verde,     badge:null },
      { nome:"Gengibre",               emoji:"🫚", peso:"250 g",      preco:"1,50 €", foto:FOTOS.gengibre,         badge:null },
      { nome:"Grelo de Couve",         emoji:"🌿", peso:"Molho",      preco:"3,50 €", foto:FOTOS.grelos,           badge:null },
      { nome:"Grelo de Nabo",          emoji:"🌿", peso:"Molho",      preco:"3,95 €", foto:FOTOS.grelos,           badge:null },
      { nome:"Hortelã",                emoji:"🌿", peso:"Molho 100g", preco:"Oferta da casa", foto:FOTOS.hortela,  badge:"🎁 Oferta", badgeClass:"badge-new" },
      { nome:"Inhame",                 emoji:"🍠", peso:"1 kg",       preco:"6,99 €", foto:FOTOS.inhame,           badge:null },
      { nome:"Maçaroca",               emoji:"🌽", peso:"1 un",       preco:"1,99 €", foto:FOTOS.milho,            badge:null },
      { nome:"Malagueta",              emoji:"🌶️", peso:"250 g",      preco:"2,95 €", foto:FOTOS.malagueta,        badge:null },
      { nome:"Mandioca",               emoji:"🥔", peso:"1 kg",       preco:"4,99 €", foto:FOTOS.mandioca,         badge:null },
      { nome:"Nabiça",                 emoji:"🌿", peso:"Molho",      preco:"2,49 €", foto:FOTOS.grelos,           badge:null },
      { nome:"Nabo",                   emoji:"🥬", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.nabo,             badge:null },
      { nome:"Pepino",                 emoji:"🥒", peso:"1 kg",       preco:"2,49 €", foto:FOTOS.pepino,           badge:null },
      { nome:"Pimento Verde",          emoji:"🫑", peso:"500 g",      preco:"1,99 €", foto:FOTOS.pimento_verde,     badge:null },
      { nome:"Pimento Vermelho",       emoji:"🫑", peso:"500 g",      preco:"1,99 €", foto:FOTOS.pimento_vermelho,  badge:null },
      { nome:"Quiabo",                 emoji:"🫛", peso:"500 g",      preco:"4,99 €", foto:FOTOS.quiabo,           badge:null },
      { nome:"Rabanete",               emoji:"🔴", peso:"500 g",      preco:"1,99 €", foto:FOTOS.rabanete,         badge:null },
      { nome:"Salsa",                  emoji:"🌿", peso:"Molho 100g", preco:"1,00 €", foto:FOTOS.salsa,            badge:null },
      { nome:"Tomate Cacho",           emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomate_cacho,      badge:null },
      { nome:"Tomate Cereja",          emoji:"🍅", peso:"500 g",      preco:"2,50 €", foto:FOTOS.tomate_cereja,     badge:null },
      { nome:"Tomate Chucha",          emoji:"🍅", peso:"1 kg",       preco:"1,99 €", foto:FOTOS.tomate_chucha,     badge:null },
      { nome:"Tomate Coração de Boi",  emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomate_coracao_boi,badge:null },
      { nome:"Tomate Rosa",            emoji:"🍅", peso:"1 kg",       preco:"2,99 €", foto:FOTOS.tomates,          badge:"💎 Premium", badgeClass:"" },
      { nome:"Tomate Salada",          emoji:"🍅", peso:"1 kg",       preco:"1,59 €", foto:FOTOS.tomate_salada,     badge:"🔥 Popular", badgeClass:"badge-hot" },
    ],
    // CABAZES — cestos prontos de frutas e/ou legumes.
    // Ajuste nomes, descrições (peso), preços e a lista `itens` conforme desejar.
    // `itens` é opcional; se existir, o cartão mostra "Ver o que leva" (abre janela com a lista).
    cabazes: [
      { nome:"Cabaz Detox",        emoji:"🥗", peso:"≈ 12 kg", preco:"48,95 €", foto:FOTOS.cabaz_detox, badge:"💚 Detox", badgeClass:"badge-bio",
        nota:"A imagem deste cabaz é meramente ilustrativa.",
        itens: [
          { grupo:"Frutas", q:"1 un",   nome:"Ananás" },
          {                 q:"1 kg",   nome:"Laranja" },
          {                 q:"500 g",  nome:"Limão" },
          {                 q:"500 g",  nome:"Kiwi" },
          {                 q:"1 kg",   nome:"Abacate" },
          {                 q:"1 kg",   nome:"Clementina" },
          {                 q:"1 kg",   nome:"Maçã Starking" },
          {                 q:"1 un",   nome:"Manga" },
          { grupo:"Legumes",q:"500 g",  nome:"Espinafres" },
          {                 q:"750 g",  nome:"Beterraba" },
          {                 q:"1 un",   nome:"Couve Coração" },
          {                 q:"1 un",   nome:"Alface" },
          {                 q:"1 kg",   nome:"Cenoura" },
          {                 q:"500 g",  nome:"Pepino" },
          {                 q:"700 g",  nome:"Curgete" },
          {                 q:"150 g",  nome:"Hortelã" },
        ] },      { nome:"Cabaz Familiar",     emoji:"🧺", peso:"Para toda a família",       preco:P, foto:FOTOS.cabaz_frutas,  badge:null },
      { nome:"Cabaz de Verão",     emoji:"🍉", peso:"Frutos da época",           preco:P, foto:FOTOS.cabaz_verao,   badge:"🌞 Verão",   badgeClass:"",
        itens: [
          { q:"1",      nome:"Melão" },
          { q:"1",      nome:"Melancia" },
          { q:"1",      nome:"Abacaxi" },
          { q:"1",      nome:"Manga" },
          { q:"1",      nome:"Papaia" },
          { q:"500 g",  nome:"Pêssego" },
          { q:"500 g",  nome:"Ameixas" },
          { q:"500 g",  nome:"Alperce" },
          { q:"125 g",  nome:"Mirtilo" },
          { q:"125 g",  nome:"Framboesas" },
          { q:"1 kg",   nome:"Banana" },
          { q:"1 kg",   nome:"Laranja" },
          { q:"1 kg",   nome:"Maçã" },
        ] },
      { nome:"Cabaz de Legumes",   emoji:"🥦", peso:"Legumes frescos p/ sopa",   preco:P, foto:FOTOS.cabaz_legumes, badge:null },
    ],
  };

  /* ═══════════════════════════════════════════════════════════
     AVALIAÇÕES — nota real do Google Business (4,9 ★ · 107 avaliações).
     Os textos abaixo são PLACEHOLDER. Substitua por avaliações reais
     copiadas do Google (nome do cliente + texto), mantendo em português.
     ═══════════════════════════════════════════════════════════ */
  const avaliacoesInfo = {
    nota: "4,9",
    total: 107,
    link: "https://maps.app.goo.gl/1gHGqMac4ahTtfxf8?g_st=ac",
    // Temas que os clientes mais destacam (tags reais do Google):
    temas: ["Frescura", "Qualidade da fruta", "Limpeza", "Variedade", "Simpatia"],
  };

  const avaliacoes = [
    { nome:"Ana Pinto", estrelas:5, texto:"Legumes e fruta com boa qualidade. Atendimento adequado e preocupação no atendimento. Preços justos para a qualidade existente. Limpeza do espaço. Cuidado na apresentação dos artigos." },
    { nome:"Pedro Martins", estrelas:5, texto:"Boa fruta, variada e a bom preço! Gosto especialmente das promoções que fazem em fruta já muito madura, com a dupla vantagem de evitar que esta vá parar ao lixo e pagando menos! Funcionários muito simpáticos e atenciosos! Localização central." },
    { nome:"Eugene Nevezhin", estrelas:5, texto:"Very good and fresh fruits and vegetables. Affordable prices." },
  ];
