/* ═══════════════════════════════════════════════════════════
   DADOS DO SITE — produtos, preços e fotos
   Para atualizar um preço: substitua `preco:P` por `preco:"1,99 €/kg"`.
   `P` é o texto mostrado quando o preço ainda não está definido.
   ═══════════════════════════════════════════════════════════ */
  const P = "A consultar";

  const FOTOS = {
    bananas:      "fotos/foto_8_1.jpeg",
    laranjas:     "fotos/foto_7_1.jpeg",
    morangos:     "fotos/foto_10_1.jpeg",
    melancia:     "fotos/foto_3_1.jpeg",
    ananas:       "fotos/foto_12_1.jpeg",
    pessegos:     "fotos/foto_6_1.jpeg",
    melao_verde:  "fotos/foto_4_1.jpeg",
    melao_branco: "fotos/foto_2_1.jpeg",
    melao_am:     "fotos/foto_5_1.jpeg",
    figos:        "fotos/foto_1_1.jpeg",
    roma:         "fotos/foto_9_1.jpeg",
    tangerina:    "fotos/foto_11_1.jpeg",
    macas:    "https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg",
    uvas:     "https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg",
    manga:    "https://images.pexels.com/photos/918643/pexels-photo-918643.jpeg",
    peras:    "https://images.pexels.com/photos/568471/pexels-photo-568471.jpeg",
    limoes:   "https://images.pexels.com/photos/1132047/pexels-photo-1132047.jpeg",
    cerejas:  "https://images.pexels.com/photos/109274/pexels-photo-109274.jpeg",
    kiwi:     "https://images.pexels.com/photos/1138723/pexels-photo-1138723.jpeg",
    abacate:  "https://images.pexels.com/photos/557659/pexels-photo-557659.jpeg",
    coco:     "https://images.pexels.com/photos/1120575/pexels-photo-1120575.jpeg",
    ameixa:   "https://images.pexels.com/photos/1028599/pexels-photo-1028599.jpeg",
    tomates:    "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg",
    cenouras:   "https://images.pexels.com/photos/143133/pexels-photo-143133.jpeg",
    brocoulos:  "https://images.pexels.com/photos/47347/broccoli-vegetable-food-healthy-47347.jpeg",
    alface:     "https://images.pexels.com/photos/2329440/pexels-photo-2329440.jpeg",
    pepino:     "https://images.pexels.com/photos/2329734/pexels-photo-2329734.jpeg",
    pimentos:   "https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg",
    cebolas:    "https://images.pexels.com/photos/175423/pexels-photo-175423.jpeg",
    alho:       "https://images.pexels.com/photos/629187/pexels-photo-629187.jpeg",
    batatas:    "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg",
    milho:      "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg",
    espinafres: "https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg",
    beringela:  "https://images.pexels.com/photos/321551/pexels-photo-321551.jpeg",
    curgete:    "https://images.pexels.com/photos/1327838/pexels-photo-1327838.jpeg",
    cogumelos:  "https://images.pexels.com/photos/1435706/pexels-photo-1435706.jpeg",
    couve:      "https://images.pexels.com/photos/2518893/pexels-photo-2518893.jpeg",
    batatadoce: "https://images.pexels.com/photos/89247/pexels-photo-89247.jpeg",
  };
  const SFX = "?auto=compress&cs=tinysrgb&w=500&h=500&fit=crop";

  function urlFoto(u) { return u.startsWith('fotos/') ? u : u + SFX; }

  const produtos = {
    frutas: [
      { nome:"Maçã Golden",         emoji:"🍎", preco:P, foto:FOTOS.macas,        badge:null },
      { nome:"Maçã Reineta",        emoji:"🍏", preco:P, foto:FOTOS.macas,        badge:null },
      { nome:"Bananas",             emoji:"🍌", preco:P, foto:FOTOS.bananas,      badge:null },
      { nome:"Laranjas",            emoji:"🍊", preco:P, foto:FOTOS.laranjas,     badge:null },
      { nome:"Tangerina",           emoji:"🍊", preco:P, foto:FOTOS.tangerina,    badge:null },
      { nome:"Uva sem Grainha",     emoji:"🍇", preco:P, foto:FOTOS.uvas,         badge:null },
      { nome:"Uva Red Globe",       emoji:"🍇", preco:P, foto:FOTOS.uvas,         badge:"⭐ Destaque", badgeClass:"" },
      { nome:"Morangos",            emoji:"🍓", preco:P, foto:FOTOS.morangos,     badge:"🔥 Popular",  badgeClass:"badge-hot" },
      { nome:"Melancia",            emoji:"🍉", preco:P, foto:FOTOS.melancia,     badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Manga",               emoji:"🥭", preco:P, foto:FOTOS.manga,        badge:"🌴 Tropical", badgeClass:"badge-new" },
      { nome:"Ananás",              emoji:"🍍", preco:P, foto:FOTOS.ananas,       badge:null },
      { nome:"Pêras",               emoji:"🍐", preco:P, foto:FOTOS.peras,        badge:null },
      { nome:"Limões",              emoji:"🍋", preco:P, foto:FOTOS.limoes,       badge:null },
      { nome:"Pêssego Amarelo",     emoji:"🍑", preco:P, foto:FOTOS.pessegos,     badge:null },
      { nome:"Pêssego Vermelho",    emoji:"🍑", preco:P, foto:FOTOS.pessegos,     badge:null },
      { nome:"Pêssego Paraguaio",   emoji:"🍑", preco:P, foto:FOTOS.pessegos,     badge:null },
      { nome:"Nectarina",           emoji:"🍑", preco:P, foto:FOTOS.pessegos,     badge:null },
      { nome:"Cereja de Fundão",    emoji:"🍒", preco:P, foto:FOTOS.cerejas,      badge:"💎 Premium",  badgeClass:"badge-hot" },
      { nome:"Cereja Gardunha 2kg", emoji:"🍒", preco:P, foto:FOTOS.cerejas,      badge:"📦 Caixa",    badgeClass:"" },
      { nome:"Figos",               emoji:"🫐", preco:P, foto:FOTOS.figos,        badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Romã",                emoji:"🔴", preco:P, foto:FOTOS.roma,         badge:null },
      { nome:"Kiwi",                emoji:"🥝", preco:P, foto:FOTOS.kiwi,         badge:null },
      { nome:"Abacate",             emoji:"🥑", preco:P, foto:FOTOS.abacate,      badge:null },
      { nome:"Coco",                emoji:"🥥", preco:P, foto:FOTOS.coco,         badge:null },
      { nome:"Melão Verde",         emoji:"🍈", preco:P, foto:FOTOS.melao_verde,  badge:null },
      { nome:"Melão Branco",        emoji:"🍈", preco:P, foto:FOTOS.melao_branco, badge:null },
      { nome:"Melão Amarelo",       emoji:"🍈", preco:P, foto:FOTOS.melao_am,     badge:"🌞 Verão",    badgeClass:"" },
      { nome:"Ameixa Vermelha",     emoji:"🍇", preco:P, foto:FOTOS.ameixa,       badge:null },
    ],
    legumes: [
      { nome:"Tomates",     emoji:"🍅", preco:P, foto:FOTOS.tomates,    badge:"🔥 Popular", badgeClass:"badge-hot" },
      { nome:"Cenouras",    emoji:"🥕", preco:P, foto:FOTOS.cenouras,   badge:null },
      { nome:"Brócolos",    emoji:"🥦", preco:P, foto:FOTOS.brocoulos,  badge:"🌱 Bio",     badgeClass:"badge-bio" },
      { nome:"Alface",      emoji:"🥬", preco:P, foto:FOTOS.alface,     badge:null },
      { nome:"Pepino",      emoji:"🥒", preco:P, foto:FOTOS.pepino,     badge:null },
      { nome:"Pimentos",    emoji:"🫑", preco:P, foto:FOTOS.pimentos,   badge:null },
      { nome:"Cebolas",     emoji:"🧅", preco:P, foto:FOTOS.cebolas,    badge:null },
      { nome:"Alho",        emoji:"🧄", preco:P, foto:FOTOS.alho,       badge:null },
      { nome:"Batatas",     emoji:"🥔", preco:P, foto:FOTOS.batatas,    badge:null },
      { nome:"Milho",       emoji:"🌽", preco:P, foto:FOTOS.milho,      badge:null },
      { nome:"Espinafres",  emoji:"🥬", preco:P, foto:FOTOS.espinafres, badge:"🌱 Bio",     badgeClass:"badge-bio" },
      { nome:"Beringela",   emoji:"🍆", preco:P, foto:FOTOS.beringela,  badge:null },
      { nome:"Curgete",     emoji:"🥒", preco:P, foto:FOTOS.curgete,    badge:null },
      { nome:"Cogumelos",   emoji:"🍄", preco:P, foto:FOTOS.cogumelos,  badge:null },
      { nome:"Couve",       emoji:"🥬", preco:P, foto:FOTOS.couve,      badge:null },
      { nome:"Batata-doce", emoji:"🍠", preco:P, foto:FOTOS.batatadoce, badge:null },
    ],
  };
